const dummy = [
  `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc eleifend viverra elit, ut eleifend nibh maximus eu. Nunc porttitor efficitur nisi, at scelerisque lacus aliquet sit amet. Integer egestas malesuada dictum. Morbi a lacus convallis, mattis sapien ac, gravida nibh. Vestibulum feugiat pretium gravida. Fusce facilisis, purus vel porta imperdiet, ante ante vestibulum lacus, eu tincidunt diam diam nec massa. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce ac leo magna. Curabitur magna dolor, bibendum quis odio rhoncus, commodo lobortis tortor. Sed mattis id sem sed euismod. Aenean tortor enim, accumsan vitae sem at, fermentum aliquet lectus. Proin consequat leo et sapien fermentum mollis. Nullam vehicula urna quis magna consequat tempus. Integer pharetra porttitor faucibus.`,
  `Phasellus sed augue sodales, tempus dui eget, iaculis leo. Nulla eget justo in orci varius pretium. Nunc egestas sapien sit amet elit gravida, in hendrerit mi aliquet. Etiam tellus massa, cursus sed porta eu, tristique finibus nisl. Cras lobortis quis dolor quis faucibus. Nam aliquam enim elit. Nunc vulputate tortor tellus, non lobortis nibh ultrices faucibus. Ut feugiat id diam eu ultrices. Morbi imperdiet nisl a sem fringilla dignissim. Phasellus sit amet euismod dolor. Etiam vitae facilisis felis. Sed arcu quam, pulvinar at felis eu, facilisis congue mauris. Proin fringilla id nisl in consectetur. Vestibulum cursus ultrices nunc, eu malesuada mauris porttitor vitae. Aliquam volutpat finibus lorem, nec tempor libero laoreet eu. Sed sollicitudin nec nisi sit amet rhoncus.`,
  `Vivamus volutpat lorem sapien, laoreet scelerisque lectus dapibus id. Nunc eget diam id mauris vestibulum pharetra. Sed efficitur finibus maximus. Nunc feugiat ipsum eu lorem condimentum rhoncus. Suspendisse vel augue vel felis condimentum vulputate in eu turpis. Quisque vitae nulla in tellus hendrerit faucibus. Donec nec dolor placerat, congue massa at, gravida mi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi nec neque id diam vehicula fermentum ut ut turpis. Suspendisse ex justo, commodo sed blandit aliquet, lacinia ac massa. Cras sit amet molestie massa, vel varius dolor. Sed maximus augue at libero molestie, non feugiat quam dictum.`,
  `Nunc ac lobortis orci, et dictum tortor. Morbi eget tortor vitae neque ultrices rutrum. Pellentesque et nibh egestas, ultrices urna eget, vulputate ante. Suspendisse id arcu ante. Aenean dignissim blandit turpis et gravida. Mauris tristique lacus et lobortis iaculis. Donec id nulla in sem feugiat molestie. Integer dictum ac arcu id feugiat. Nunc lobortis sodales dolor, id sodales purus cursus nec. Integer quis urna id magna euismod elementum. Duis ante lectus, aliquet a dictum at, cursus ut tortor. Aenean interdum, sem nec vehicula dictum, ipsum enim tincidunt enim, tristique ultricies enim dolor in est.`,
  `Vestibulum a porta lectus. Mauris faucibus tortor eu venenatis commodo. Quisque sit amet magna in felis posuere viverra ut nec libero. Curabitur vel ligula lacus. Suspendisse sit amet velit vitae nisl pharetra facilisis. Curabitur consequat massa enim. Integer convallis mi non purus semper lobortis. Vivamus quis interdum tellus. Curabitur non ligula sed velit mattis blandit vitae at massa. Pellentesque pretium blandit pretium.`,
  `Ut et tristique justo. Curabitur et libero sit amet nisl commodo tristique non luctus ipsum. Nullam condimentum aliquam nulla et interdum. Aliquam eu pellentesque lacus. Maecenas suscipit orci velit, ut viverra tortor aliquam a. Ut pellentesque erat nec pellentesque luctus. Aliquam quis tortor vitae ipsum pellentesque porta sit amet in neque. Sed risus sem, vulputate in convallis sed, lobortis eget augue. Nullam eu iaculis est, sit amet ultricies sem. Morbi id vestibulum nisl, vel elementum mauris.`,
  `Aliquam pellentesque laoreet auctor. Donec turpis nibh, porttitor vel nunc in, aliquet porttitor sem. Aenean ultrices quam at dolor suscipit, non dapibus ante faucibus. In vitae sapien mi. Integer non eros est. Integer lacinia leo vitae justo pulvinar bibendum. Curabitur tincidunt, ipsum vitae finibus sollicitudin, ligula metus semper neque, in semper lacus neque eget turpis. Mauris rhoncus eu nisl ut ultricies. Suspendisse potenti. Mauris sit amet semper sapien. Fusce aliquet varius lectus, ullamcorper condimentum dolor venenatis in. Suspendisse potenti. Fusce volutpat, diam eget sagittis commodo, libero quam viverra urna, sed lobortis dolor nisi quis ante. Nulla sed erat id quam efficitur fringilla. Curabitur egestas feugiat viverra.`,
  `Donec et facilisis tortor. Donec eget placerat lacus, et pellentesque libero. Morbi commodo ante a erat feugiat posuere. Pellentesque ac eleifend dolor. Cras sit amet viverra elit. Mauris magna eros, suscipit et sodales id, mollis quis lacus. Sed at diam nibh. Nam accumsan sem odio, non condimentum mi viverra porta. Vivamus metus lorem, mollis gravida mattis ut, eleifend vel odio. Vestibulum pretium eros ac molestie consequat. Suspendisse convallis bibendum nulla a cursus. Donec sodales ornare tincidunt. Phasellus auctor lacus quis ligula placerat, tristique mattis turpis rhoncus. Sed imperdiet quis turpis sit amet fringilla.`,
  `Sed cursus nisl a ex facilisis aliquet hendrerit sit amet ante. Cras elementum sagittis ultricies. Aliquam mauris urna, maximus et tincidunt ut, tristique vitae tellus. In euismod maximus massa sed tristique. Sed nec posuere arcu, ac pretium enim. Suspendisse non libero eu est sodales aliquam sed ut ante. Praesent sit amet mollis lacus, sit amet molestie erat. Cras fermentum luctus imperdiet.`,
  `Nunc tempor hendrerit accumsan. Sed condimentum enim eu facilisis pharetra. Vivamus semper consequat quam, eget gravida nisi interdum non. Maecenas vitae faucibus dolor. Curabitur congue egestas quam in sagittis. Aliquam a nisi vestibulum, dapibus turpis eu, dictum mi. Donec sit amet ipsum sed dolor posuere mollis. Proin in varius eros.`,
  `Nunc ac lobortis orci, et dictum tortor. Morbi eget tortor vitae neque ultrices rutrum. Pellentesque et nibh egestas, ultrices urna eget, vulputate ante. Suspendisse id arcu ante. Aenean dignissim blandit turpis et gravida. Mauris tristique lacus et lobortis iaculis. Donec id nulla in sem feugiat molestie. Integer dictum ac arcu id feugiat. Nunc lobortis sodales dolor, id sodales purus cursus nec. Integer quis urna id magna euismod elementum. Duis ante lectus, aliquet a dictum at, cursus ut tortor. Aenean interdum, sem nec vehicula dictum, ipsum enim tincidunt enim, tristique ultricies enim dolor in est.`,
  `Vestibulum a porta lectus. Mauris faucibus tortor eu venenatis commodo. Quisque sit amet magna in felis posuere viverra ut nec libero. Curabitur vel ligula lacus. Suspendisse sit amet velit vitae nisl pharetra facilisis. Curabitur consequat massa enim. Integer convallis mi non purus semper lobortis. Vivamus quis interdum tellus. Curabitur non ligula sed velit mattis blandit vitae at massa. Pellentesque pretium blandit pretium.`,
  `Ut et tristique justo. Curabitur et libero sit amet nisl commodo tristique non luctus ipsum. Nullam condimentum aliquam nulla et interdum. Aliquam eu pellentesque lacus. Maecenas suscipit orci velit, ut viverra tortor aliquam a. Ut pellentesque erat nec pellentesque luctus. Aliquam quis tortor vitae ipsum pellentesque porta sit amet in neque. Sed risus sem, vulputate in convallis sed, lobortis eget augue. Nullam eu iaculis est, sit amet ultricies sem. Morbi id vestibulum nisl, vel elementum mauris.`,
  `Aliquam pellentesque laoreet auctor. Donec turpis nibh, porttitor vel nunc in, aliquet porttitor sem. Aenean ultrices quam at dolor suscipit, non dapibus ante faucibus. In vitae sapien mi. Integer non eros est. Integer lacinia leo vitae justo pulvinar bibendum. Curabitur tincidunt, ipsum vitae finibus sollicitudin, ligula metus semper neque, in semper lacus neque eget turpis. Mauris rhoncus eu nisl ut ultricies. Suspendisse potenti. Mauris sit amet semper sapien. Fusce aliquet varius lectus, ullamcorper condimentum dolor venenatis in. Suspendisse potenti. Fusce volutpat, diam eget sagittis commodo, libero quam viverra urna, sed lobortis dolor nisi quis ante. Nulla sed erat id quam efficitur fringilla. Curabitur egestas feugiat viverra.`,
  `Donec et facilisis tortor. Donec eget placerat lacus, et pellentesque libero. Morbi commodo ante a erat feugiat posuere. Pellentesque ac eleifend dolor. Cras sit amet viverra elit. Mauris magna eros, suscipit et sodales id, mollis quis lacus. Sed at diam nibh. Nam accumsan sem odio, non condimentum mi viverra porta. Vivamus metus lorem, mollis gravida mattis ut, eleifend vel odio. Vestibulum pretium eros ac molestie consequat. Suspendisse convallis bibendum nulla a cursus. Donec sodales ornare tincidunt. Phasellus auctor lacus quis ligula placerat, tristique mattis turpis rhoncus. Sed imperdiet quis turpis sit amet fringilla.`,
];

export default dummy;
