import React from 'react'
import PeekElement from 'react-peek-element'

import './App.css'

function App() {
  return (
    <div className="App">
      <PeekElement usePlaceHolder>
        <header >
          menu items
        </header>
      </PeekElement>
      
      <div className='main-content'>
        <p>I'm baby vegan lo-fi tote bag neutra austin cardigan poutine offal distillery bicycle rights cliche. Affogato quinoa master cleanse wayfarers portland swag occupy. Affogato asymmetrical chicharrones, post-ironic pinterest forage selfies. Asymmetrical you probably haven't heard of them before they sold out cray. Selfies fingerstache keytar synth.</p>
        <p>Seitan vice gluten-free, farm-to-table yuccie pabst chartreuse post-ironic banh mi waistcoat woke tilde. Mixtape microdosing taiyaki, distillery yuccie man braid humblebrag actually venmo vinyl. Sustainable try-hard occupy franzen cliche tilde four dollar toast kombucha put a bird on it. Butcher venmo trust fund yr gentrify coloring book bicycle rights blog. Mustache truffaut cronut kitsch readymade portland pok pok gastropub gentrify fixie disrupt forage. Venmo pop-up affogato ethical fixie subway tile keffiyeh you probably haven't heard of them seitan try-hard intelligentsia hammock.</p>
        <p>Waistcoat helvetica brooklyn offal plaid hell of XOXO messenger bag bespoke umami succulents williamsburg. Raw denim activated charcoal church-key mixtape narwhal health goth mlkshk freegan glossier enamel pin poke. Cold-pressed paleo fixie YOLO pork belly whatever. Quinoa twee knausgaard you probably haven't heard of them, keytar street art activated charcoal fingerstache echo park mustache put a bird on it migas deep v selvage. Raw denim art party retro seitan small batch offal tumeric cardigan street art pinterest.</p>
        <p>Authentic fixie master cleanse poutine leggings wolf man braid meditation, vexillologist retro. Heirloom man bun wolf, disrupt fingerstache gochujang food truck yuccie activated charcoal hot chicken thundercats semiotics iPhone normcore. Synth artisan bushwick unicorn drinking vinegar intelligentsia fingerstache shaman. Kombucha deep v flannel selvage microdosing hot chicken, drinking vinegar artisan literally vexillologist. Everyday carry cornhole roof party affogato small batch. Hot chicken cardigan kitsch kogi wayfarers vice crucifix distillery asymmetrical migas. Lumbersexual flannel sartorial hexagon cred succulents forage.</p>
        <p>Twee dreamcatcher marfa listicle 8-bit. Put a bird on it affogato gochujang taiyaki. Tilde keytar offal mixtape. Single-origin coffee cray drinking vinegar humblebrag blue bottle pour-over cronut. Deep v organic pork belly, copper mug vaporware cold-pressed woke venmo waistcoat slow-carb food truck yuccie microdosing lumbersexual banh mi.</p>
        <p>I'm baby vegan lo-fi tote bag neutra austin cardigan poutine offal distillery bicycle rights cliche. Affogato quinoa master cleanse wayfarers portland swag occupy. Affogato asymmetrical chicharrones, post-ironic pinterest forage selfies. Asymmetrical you probably haven't heard of them before they sold out cray. Selfies fingerstache keytar synth.</p>
        <p>Seitan vice gluten-free, farm-to-table yuccie pabst chartreuse post-ironic banh mi waistcoat woke tilde. Mixtape microdosing taiyaki, distillery yuccie man braid humblebrag actually venmo vinyl. Sustainable try-hard occupy franzen cliche tilde four dollar toast kombucha put a bird on it. Butcher venmo trust fund yr gentrify coloring book bicycle rights blog. Mustache truffaut cronut kitsch readymade portland pok pok gastropub gentrify fixie disrupt forage. Venmo pop-up affogato ethical fixie subway tile keffiyeh you probably haven't heard of them seitan try-hard intelligentsia hammock.</p>
        <p>Waistcoat helvetica brooklyn offal plaid hell of XOXO messenger bag bespoke umami succulents williamsburg. Raw denim activated charcoal church-key mixtape narwhal health goth mlkshk freegan glossier enamel pin poke. Cold-pressed paleo fixie YOLO pork belly whatever. Quinoa twee knausgaard you probably haven't heard of them, keytar street art activated charcoal fingerstache echo park mustache put a bird on it migas deep v selvage. Raw denim art party retro seitan small batch offal tumeric cardigan street art pinterest.</p>
        <p>Authentic fixie master cleanse poutine leggings wolf man braid meditation, vexillologist retro. Heirloom man bun wolf, disrupt fingerstache gochujang food truck yuccie activated charcoal hot chicken thundercats semiotics iPhone normcore. Synth artisan bushwick unicorn drinking vinegar intelligentsia fingerstache shaman. Kombucha deep v flannel selvage microdosing hot chicken, drinking vinegar artisan literally vexillologist. Everyday carry cornhole roof party affogato small batch. Hot chicken cardigan kitsch kogi wayfarers vice crucifix distillery asymmetrical migas. Lumbersexual flannel sartorial hexagon cred succulents forage.</p>
        <p>Twee dreamcatcher marfa listicle 8-bit. Put a bird on it affogato gochujang taiyaki. Tilde keytar offal mixtape. Single-origin coffee cray drinking vinegar humblebrag blue bottle pour-over cronut. Deep v organic pork belly, copper mug vaporware cold-pressed woke venmo waistcoat slow-carb food truck yuccie microdosing lumbersexual banh mi.</p>
        <p>I'm baby vegan lo-fi tote bag neutra austin cardigan poutine offal distillery bicycle rights cliche. Affogato quinoa master cleanse wayfarers portland swag occupy. Affogato asymmetrical chicharrones, post-ironic pinterest forage selfies. Asymmetrical you probably haven't heard of them before they sold out cray. Selfies fingerstache keytar synth.</p>
        <p>Seitan vice gluten-free, farm-to-table yuccie pabst chartreuse post-ironic banh mi waistcoat woke tilde. Mixtape microdosing taiyaki, distillery yuccie man braid humblebrag actually venmo vinyl. Sustainable try-hard occupy franzen cliche tilde four dollar toast kombucha put a bird on it. Butcher venmo trust fund yr gentrify coloring book bicycle rights blog. Mustache truffaut cronut kitsch readymade portland pok pok gastropub gentrify fixie disrupt forage. Venmo pop-up affogato ethical fixie subway tile keffiyeh you probably haven't heard of them seitan try-hard intelligentsia hammock.</p>
        <p>Waistcoat helvetica brooklyn offal plaid hell of XOXO messenger bag bespoke umami succulents williamsburg. Raw denim activated charcoal church-key mixtape narwhal health goth mlkshk freegan glossier enamel pin poke. Cold-pressed paleo fixie YOLO pork belly whatever. Quinoa twee knausgaard you probably haven't heard of them, keytar street art activated charcoal fingerstache echo park mustache put a bird on it migas deep v selvage. Raw denim art party retro seitan small batch offal tumeric cardigan street art pinterest.</p>
        <p>Authentic fixie master cleanse poutine leggings wolf man braid meditation, vexillologist retro. Heirloom man bun wolf, disrupt fingerstache gochujang food truck yuccie activated charcoal hot chicken thundercats semiotics iPhone normcore. Synth artisan bushwick unicorn drinking vinegar intelligentsia fingerstache shaman. Kombucha deep v flannel selvage microdosing hot chicken, drinking vinegar artisan literally vexillologist. Everyday carry cornhole roof party affogato small batch. Hot chicken cardigan kitsch kogi wayfarers vice crucifix distillery asymmetrical migas. Lumbersexual flannel sartorial hexagon cred succulents forage.</p>
        <p>Twee dreamcatcher marfa listicle 8-bit. Put a bird on it affogato gochujang taiyaki. Tilde keytar offal mixtape. Single-origin coffee cray drinking vinegar humblebrag blue bottle pour-over cronut. Deep v organic pork belly, copper mug vaporware cold-pressed woke venmo waistcoat slow-carb food truck yuccie microdosing lumbersexual banh mi.</p>
      </div>
      <footer />
    </div>
  );
}

export default App;
